// src/ui/components/tables/CreateTableModal.vue
<template>
  <NModal v-model:show="show" title="Create Table" size="medium" preset="card" style="width: 600px">
    <NForm ref="formRef" :model="form" :rules="rules">
      <NFormItem path="sql" label="SQL Statement">
        <NInput
          v-model:value="form.sql"
          type="textarea"
          placeholder="CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT UNIQUE
);"
          :autosize="{ minRows: 6, maxRows: 16 }"
          :disabled="loading"
          style="font-family: monospace; font-size: 13px"
        />
      </NFormItem>
      <NAlert type="info" style="margin-bottom: 8px">
        Use double-quotes for column names that are SQL keywords, e.g., <NText code>"order"</NText>.
      </NAlert>
    </NForm>
    <NAlert v-if="error" type="error" :title="error" style="margin-top: 12px" />

    <template #footer>
      <NSpace justify="end">
        <NButton @click="show = false">Cancel</NButton>
        <NButton type="primary" :loading="loading" @click="handleCreate">Create Table</NButton>
      </NSpace>
    </template>
  </NModal>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { NModal, NForm, NFormItem, NInput, NButton, NSpace, NAlert, NText, type FormRules, type FormInst } from 'naive-ui';
import { useAuthStore } from '@/stores/auth';
import { useNotificationStore } from '@/stores/notification';

const show = defineModel<boolean>('show', { default: false });
const emit = defineEmits<{ success: [] }>();

const authStore = useAuthStore();
const notif = useNotificationStore();

const formRef = ref<FormInst | null>(null);
const loading = ref(false);
const error = ref('');
const form = ref({ sql: '' });

const rules: FormRules = {
  sql: [
    { required: true, message: 'SQL is required', trigger: 'blur' },
    { min: 10, message: 'SQL must be at least 10 characters', trigger: 'blur' },
    {
      validator: (_rule, value: string) => {
        if (!value.trim().toUpperCase().startsWith('CREATE TABLE')) {
          return new Error('SQL must start with CREATE TABLE');
        }
        return true;
      },
      trigger: 'blur',
    },
  ],
};

watch(show, (val) => {
  if (!val) { form.value.sql = ''; error.value = ''; }
});

async function handleCreate() {
  try { await formRef.value?.validate(); } catch { return; }
  loading.value = true;
  error.value = '';
  try {
    const res = await authStore.apiClient.createTable(form.value.sql);
    if (res.success !== false) {
      notif.showToast({ message: 'Table created', type: 'success' });
      show.value = false;
      emit('success');
    } else {
      error.value = res.error ?? 'Failed to create table';
    }
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Failed to create table';
  } finally {
    loading.value = false;
  }
}
</script>

// src/ui/components/Tables/CreateTableModal.tsx
import { useState } from 'preact/hooks';
import { Modal, Button, Alert, FormField } from '../shared';
import { ApiClient } from '../../lib/api';
import { useNotification } from '../../contexts/NotificationContext';
import { useFormValidation } from '../../hooks/useFormValidation';

interface CreateTableModalProps {
  isOpen: boolean;
  onClose: () => void;
  apiClient: ApiClient;
  onSuccess: () => void;
}

export function CreateTableModal({ isOpen, onClose, apiClient, onSuccess }: CreateTableModalProps) {
  const { showToast } = useNotification();
  const [sql, setSql] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const { errors, touched, validate, handleBlur, clearAllErrors } = useFormValidation({
    sql: {
      required: true,
      minLength: 10,
      custom: (value) => {
        if (value && !value.trim().toLowerCase().startsWith('create table')) {
          return 'SQL statement must start with CREATE TABLE';
        }
        return null;
      }
    }
  });

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    setError('');

    // Validate form
    if (!validate({ sql })) {
      return;
    }

    setLoading(true);

    try {
      const result = await apiClient.createTable(sql);
      if (result.success) {
        showToast({ message: 'Table created successfully!', variant: 'success' });
        setSql('');
        clearAllErrors();
        onSuccess();
        onClose();
      } else {
        throw new Error(result.error);
      }
    } catch (err: any) {
      setError(err.message || 'Failed to create table');
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setSql('');
    setError('');
    clearAllErrors();
    onClose();
  };

  return (
    <Modal isOpen={isOpen} onClose={handleClose} title="Create Table" size="large">
      <form onSubmit={handleSubmit}>
        {error && <Alert variant="danger">{error}</Alert>}

        <FormField
          label="SQL Statement"
          name="sql"
          error={errors.sql}
          touched={touched.sql}
          required
          hint='Enter a CREATE TABLE statement. Use double quotes for SQL keywords: "update", "delete", "order", etc.'
        >
          <textarea
            className={`form-control ${errors.sql && touched.sql ? 'error' : ''}`}
            placeholder="CREATE TABLE users (&#10;  id INTEGER PRIMARY KEY AUTOINCREMENT,&#10;  name TEXT NOT NULL,&#10;  email TEXT UNIQUE,&#10;  &quot;update&quot; TEXT,&#10;  &quot;order&quot; INTEGER&#10;);"
            value={sql}
            onInput={(e) => setSql((e.target as HTMLTextAreaElement).value)}
            onBlur={() => handleBlur('sql', sql)}
            rows={12}
          />
        </FormField>

        <Alert variant="info">
          <strong>💡 提示：</strong>如果字段名或表名是 SQL 关键字（如 update, delete, order, select 等），请使用双引号包裹，例如：<code>"update"</code>, <code>"delete"</code>
        </Alert>

        <div className="modal-footer">
          <Button type="button" onClick={handleClose} variant="secondary" disabled={loading}>
            Cancel
          </Button>
          <Button type="submit" variant="success" disabled={loading}>
            {loading ? 'Creating...' : '✓ Create Table'}
          </Button>
        </div>
      </form>
    </Modal>
  );
}
