// src/ui/components/tables/VisualTableBuilder.vue
<template>
  <NModal v-model:show="show" title="Visual Table Builder" preset="card" style="width: 780px">
    <div style="display: flex; gap: 16px">
      <!-- Left: Config -->
      <div style="flex: 1">
        <NFormItem label="Table Name" :show-feedback="!!tableNameError">
          <NInput v-model:value="tableName" placeholder="my_table" @blur="validateTableName" />
          <template #feedback>{{ tableNameError }}</template>
        </NFormItem>

        <NDivider />

        <div v-for="(field, idx) in fields" :key="field.id" class="field-row">
          <NInput v-model:value="field.name" placeholder="column_name" size="small" style="width: 130px" />
          <NSelect
            v-model:value="field.type"
            :options="typeOptions"
            size="small"
            style="width: 120px"
            @update:value="(v) => onTypeChange(idx, v)"
          />
          <NSpace size="small" align="center">
            <NTooltip trigger="hover">
              <template #trigger>
                <NCheckbox v-model:checked="field.isPrimaryKey" @update:checked="(v) => onPKChange(idx, v)">PK</NCheckbox>
              </template>
              Primary Key
            </NTooltip>
            <NTooltip trigger="hover">
              <template #trigger>
                <NCheckbox v-model:checked="field.autoIncrement" :disabled="!field.isPrimaryKey || field.type !== 'INTEGER'">AI</NCheckbox>
              </template>
              Auto Increment (INTEGER PK only)
            </NTooltip>
            <NTooltip trigger="hover">
              <template #trigger>
                <NCheckbox v-model:checked="field.notNull">NN</NCheckbox>
              </template>
              Not Null
            </NTooltip>
            <NTooltip trigger="hover">
              <template #trigger>
                <NCheckbox v-model:checked="field.unique">UQ</NCheckbox>
              </template>
              Unique
            </NTooltip>
          </NSpace>
          <NInput v-model:value="field.defaultValue" placeholder="default" size="small" style="width: 80px" />
          <NButton text type="error" size="small" :disabled="fields.length <= 1" @click="removeField(idx)">
            <template #icon><Trash2 :size="13" /></template>
          </NButton>
        </div>

        <NButton dashed block style="margin-top: 8px" @click="addField">
          <template #icon><Plus :size="13" /></template>
          Add Column
        </NButton>
      </div>

      <!-- Right: SQL Preview -->
      <div style="flex: 1">
        <div class="sql-preview-label">SQL Preview</div>
        <NCode :code="generatedSQL" language="sql" style="font-size: 12px; max-height: 400px; overflow: auto" />
      </div>
    </div>

    <NAlert v-if="error" type="error" :title="error" style="margin-top: 12px" />

    <template #footer>
      <NSpace justify="end">
        <NButton @click="show = false">Cancel</NButton>
        <NButton type="primary" :loading="loading" @click="handleCreate">Create Table</NButton>
      </NSpace>
    </template>
  </NModal>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import {
  NModal, NFormItem, NInput, NSelect, NCheckbox, NCode, NDivider,
  NButton, NSpace, NAlert, NTooltip, type SelectOption,
} from 'naive-ui';
import { Plus, Trash2 } from '@lucide/vue';
import { useAuthStore } from '@/stores/auth';
import { useNotificationStore } from '@/stores/notification';

const show = defineModel<boolean>('show', { default: false });
const emit = defineEmits<{ success: [] }>();

const authStore = useAuthStore();
const notif = useNotificationStore();
const loading = ref(false);
const error = ref('');
const tableName = ref('');
const tableNameError = ref('');
let idCounter = 0;

interface Field {
  id: number;
  name: string;
  type: string;
  isPrimaryKey: boolean;
  autoIncrement: boolean;
  notNull: boolean;
  unique: boolean;
  defaultValue: string;
}

const fields = ref<Field[]>([
  { id: idCounter++, name: 'id', type: 'INTEGER', isPrimaryKey: true, autoIncrement: true, notNull: false, unique: false, defaultValue: '' },
]);

const typeOptions: SelectOption[] = [
  'INTEGER', 'TEXT', 'REAL', 'BLOB', 'NUMERIC',
  'UUID', 'DATETIME', 'TIMESTAMP', 'DATE', 'TIME', 'BOOLEAN', 'JSON',
].map(t => ({ label: t, value: t }));

const TYPE_MAP: Record<string, string> = {
  UUID: 'TEXT', DATETIME: 'TEXT', TIMESTAMP: 'TEXT', DATE: 'TEXT',
  TIME: 'TEXT', BOOLEAN: 'INTEGER', JSON: 'TEXT',
};

function quoteIdent(name: string) {
  return `"${name.replace(/"/g, '""')}"`;
}

const generatedSQL = computed(() => {
  if (!tableName.value) return '-- Enter a table name to preview SQL';
  const pks = fields.value.filter(f => f.isPrimaryKey);
  const lines: string[] = [];
  for (const f of fields.value) {
    const sqlType = TYPE_MAP[f.type] ?? f.type;
    let def = `  ${quoteIdent(f.name)} ${sqlType}`;
    if (f.isPrimaryKey && pks.length === 1) def += ' PRIMARY KEY';
    if (f.isPrimaryKey && f.autoIncrement && f.type === 'INTEGER' && pks.length === 1) def += ' AUTOINCREMENT';
    if (f.notNull && !f.isPrimaryKey) def += ' NOT NULL';
    if (f.unique && !f.isPrimaryKey) def += ' UNIQUE';
    if (f.defaultValue) def += ` DEFAULT ${f.defaultValue}`;
    lines.push(def);
  }
  if (pks.length > 1) {
    lines.push(`  PRIMARY KEY (${pks.map(f => quoteIdent(f.name)).join(', ')})`);
  }
  return `CREATE TABLE ${quoteIdent(tableName.value)} (\n${lines.join(',\n')}\n);`;
});

function addField() {
  fields.value.push({ id: idCounter++, name: '', type: 'TEXT', isPrimaryKey: false, autoIncrement: false, notNull: false, unique: false, defaultValue: '' });
}

function removeField(idx: number) {
  if (fields.value.length > 1) fields.value.splice(idx, 1);
}

function onTypeChange(idx: number, type: string) {
  if (type !== 'INTEGER') fields.value[idx].autoIncrement = false;
}

function onPKChange(idx: number, val: boolean) {
  if (!val) fields.value[idx].autoIncrement = false;
}

function validateTableName() {
  const v = tableName.value.trim();
  if (!v) { tableNameError.value = 'Table name is required'; return false; }
  if (!/^[a-zA-Z_][a-zA-Z0-9_]{0,63}$/.test(v)) {
    tableNameError.value = 'Only letters, numbers, underscores; must not start with a number';
    return false;
  }
  tableNameError.value = '';
  return true;
}

async function handleCreate() {
  if (!validateTableName()) return;
  const invalidFields = fields.value.filter(f => !f.name.trim());
  if (invalidFields.length > 0) {
    error.value = 'All columns must have a name';
    return;
  }
  loading.value = true;
  error.value = '';
  try {
    const res = await authStore.apiClient.createTable(generatedSQL.value);
    if (res.success !== false) {
      notif.showToast({ message: 'Table created', type: 'success' });
      show.value = false;
      emit('success');
      // Reset
      tableName.value = '';
      fields.value = [{ id: idCounter++, name: 'id', type: 'INTEGER', isPrimaryKey: true, autoIncrement: true, notNull: false, unique: false, defaultValue: '' }];
    } else {
      error.value = res.error ?? 'Failed to create table';
    }
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Failed to create table';
  } finally {
    loading.value = false;
  }
}
</script>

<style scoped>
.field-row {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-bottom: 8px;
  flex-wrap: nowrap;
}

.sql-preview-label {
  font-size: 12px;
  font-weight: 600;
  color: #999;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  margin-bottom: 8px;
}
</style>

// src/ui/components/Tables/VisualTableBuilder.tsx
import { useState } from 'preact/hooks';
import { Modal } from '../shared/Modal';
import { Button } from '../shared/Button';
import { FormField } from '../shared/FormField';
import { useNotification } from '../../contexts/NotificationContext';
import { useFormValidation } from '../../hooks/useFormValidation';

interface Field {
  id: string;
  name: string;
  type: string;
  isPrimaryKey: boolean;
  autoIncrement: boolean;
  notNull: boolean;
  unique: boolean;
  defaultValue: string;
}

interface VisualTableBuilderProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  apiClient: any;
}

const FIELD_TYPES = [
  { value: 'INTEGER', label: 'INTEGER', description: 'Whole numbers' },
  { value: 'TEXT', label: 'TEXT', description: 'String/text data' },
  { value: 'REAL', label: 'REAL', description: 'Decimal numbers' },
  { value: 'BLOB', label: 'BLOB', description: 'Binary data' },
  { value: 'UUID', label: 'UUID', description: 'Unique identifier (stored as TEXT)' },
  { value: 'DATETIME', label: 'DATETIME', description: 'Date and time (stored as TEXT)' },
  { value: 'DATE', label: 'DATE', description: 'Date only (stored as TEXT)' },
  { value: 'TIME', label: 'TIME', description: 'Time only (stored as TEXT)' },
  { value: 'BOOLEAN', label: 'BOOLEAN', description: 'True/false (stored as INTEGER)' },
  { value: 'JSON', label: 'JSON', description: 'JSON data (stored as TEXT)' },
];

export function VisualTableBuilder({ isOpen, onClose, onSuccess, apiClient }: VisualTableBuilderProps) {
  const { showToast } = useNotification();
  const [tableName, setTableName] = useState('');
  const [fields, setFields] = useState<Field[]>([
    {
      id: '1',
      name: 'id',
      type: 'INTEGER',
      isPrimaryKey: true,
      autoIncrement: true,
      notNull: true,
      unique: false,
      defaultValue: '',
    },
  ]);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const { errors, touched, validate, handleBlur, clearAllErrors } = useFormValidation({
    tableName: {
      required: true,
      minLength: 1,
      maxLength: 64,
      custom: (value) => {
        if (value && !/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(value)) {
          return 'Table name must start with a letter or underscore and contain only letters, numbers, and underscores';
        }
        return null;
      }
    }
  });

  const addField = () => {
    const newField: Field = {
      id: Date.now().toString(),
      name: '',
      type: 'TEXT',
      isPrimaryKey: false,
      autoIncrement: false,
      notNull: false,
      unique: false,
      defaultValue: '',
    };
    setFields([...fields, newField]);
  };

  const removeField = (id: string) => {
    if (fields.length === 1) {
      setError('Table must have at least one field');
      return;
    }
    setFields(fields.filter((f) => f.id !== id));
  };

  const updateField = (id: string, updates: Partial<Field>) => {
    setFields(
      fields.map((f) =>
        f.id === id
          ? {
              ...f,
              ...updates,
              // Auto-uncheck incompatible options
              autoIncrement:
                updates.type && updates.type !== 'INTEGER' ? false : updates.autoIncrement ?? f.autoIncrement,
            }
          : f
      )
    );
  };

  const togglePrimaryKey = (id: string) => {
    setFields(
      fields.map((f) =>
        f.id === id
          ? { ...f, isPrimaryKey: !f.isPrimaryKey, notNull: !f.isPrimaryKey || f.notNull }
          : f
      )
    );
  };

  const generateSQL = (): string => {
    if (!tableName.trim()) return '-- Enter table name';
    if (fields.length === 0) return '-- Add at least one field';
    if (fields.some((f) => !f.name.trim())) return '-- All fields must have names';

    const primaryKeys = fields.filter((f) => f.isPrimaryKey);
    const fieldDefinitions = fields.map((f) => {
      let def = `  ${f.name} `;

      // Map special types to SQLite types
      const typeMap: Record<string, string> = {
        UUID: 'TEXT',
        DATETIME: 'TEXT',
        DATE: 'TEXT',
        TIME: 'TEXT',
        BOOLEAN: 'INTEGER',
        JSON: 'TEXT',
      };
      def += typeMap[f.type] || f.type;

      // Primary key (for single PK with auto-increment)
      if (f.isPrimaryKey && primaryKeys.length === 1 && f.autoIncrement && f.type === 'INTEGER') {
        def += ' PRIMARY KEY AUTOINCREMENT';
      }

      // Constraints
      if (f.notNull && !f.isPrimaryKey) {
        def += ' NOT NULL';
      }

      if (f.unique && !f.isPrimaryKey) {
        def += ' UNIQUE';
      }

      if (f.defaultValue.trim()) {
        // Smart quote handling
        const needsQuotes = ['TEXT', 'UUID', 'DATETIME', 'DATE', 'TIME', 'JSON'].includes(f.type);
        const value = needsQuotes ? `'${f.defaultValue}'` : f.defaultValue;
        def += ` DEFAULT ${value}`;
      }

      return def;
    });

    let sql = `CREATE TABLE ${tableName} (\n${fieldDefinitions.join(',\n')}`;

    // Composite primary key or non-auto-increment single PK
    if (primaryKeys.length > 1 || (primaryKeys.length === 1 && (!primaryKeys[0].autoIncrement || primaryKeys[0].type !== 'INTEGER'))) {
      const pkFields = primaryKeys.map((f) => f.name).join(', ');
      sql += `,\n  PRIMARY KEY (${pkFields})`;
    }

    sql += '\n);';
    return sql;
  };

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    setError('');

    // Validate table name
    if (!validate({ tableName })) {
      return;
    }

    // Validate field names
    if (fields.some((f) => !f.name.trim())) {
      setError('All fields must have names');
      return;
    }

    const sql = generateSQL();
    setLoading(true);

    try {
      const result = await apiClient.createTable(sql);
      if (result.success) {
        showToast({ message: 'Table created successfully!', variant: 'success' });
        clearAllErrors();
        onSuccess();
        handleClose();
      } else {
        throw new Error(result.error);
      }
    } catch (err: any) {
      setError(err.message || 'Failed to create table');
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setTableName('');
    setFields([
      {
        id: '1',
        name: 'id',
        type: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        notNull: true,
        unique: false,
        defaultValue: '',
      },
    ]);
    setError('');
    clearAllErrors();
    onClose();
  };

  const sql = generateSQL();

  return (
    <Modal isOpen={isOpen} onClose={handleClose} title="🎨 Visual Table Builder" size="large">
      <form onSubmit={handleSubmit}>
          {error && (
            <div className="alert alert-danger">
              <span>⚠️</span>
              <span>{error}</span>
            </div>
          )}

          <FormField
            label="Table Name"
            name="tableName"
            error={errors.tableName}
            touched={touched.tableName}
            required
            hint="Must start with a letter or underscore, contain only letters, numbers, and underscores"
          >
            <input
              type="text"
              id="tableName"
              className={`form-control ${errors.tableName && touched.tableName ? 'error' : ''}`}
              placeholder="e.g., users, products, orders"
              value={tableName}
              onInput={(e) => setTableName((e.target as HTMLInputElement).value)}
              onBlur={() => handleBlur('tableName', tableName)}
            />
          </FormField>

          <div className="field-builder">
            <div className="field-builder-header">
              <h4>Fields</h4>
              <Button type="button" onClick={addField} variant="success" className="btn-sm">
                ➕ Add Field
              </Button>
            </div>

            <div className="field-list">
              {fields.map((field, index) => (
                <div key={field.id} className="field-card">
                  <div className="field-card-header">
                    <span className="field-number">#{index + 1}</span>
                    <input
                      type="text"
                      className="form-control field-name-input"
                      placeholder="Field name (required)"
                      value={field.name}
                      onInput={(e) => updateField(field.id, { name: (e.target as HTMLInputElement).value })}
                    />
                    <button
                      type="button"
                      className="btn btn-danger btn-sm"
                      onClick={() => removeField(field.id)}
                      disabled={fields.length === 1}
                    >
                      🗑️
                    </button>
                  </div>

                  <div className="field-card-body">
                    <div className="field-row">
                      <div className="form-group">
                        <label>Type</label>
                        <select
                          className="form-control"
                          value={field.type}
                          onChange={(e) => updateField(field.id, { type: (e.target as HTMLSelectElement).value })}
                        >
                          {FIELD_TYPES.map((type) => (
                            <option key={type.value} value={type.value} title={type.description}>
                              {type.label}
                            </option>
                          ))}
                        </select>
                      </div>

                      <div className="form-group">
                        <label>Default Value</label>
                        <input
                          type="text"
                          className="form-control"
                          placeholder="Optional"
                          value={field.defaultValue}
                          onInput={(e) =>
                            updateField(field.id, { defaultValue: (e.target as HTMLInputElement).value })
                          }
                        />
                      </div>
                    </div>

                    <div className="field-constraints">
                      <div className="checkbox-group">
                        <input
                          type="checkbox"
                          id={`pk-${field.id}`}
                          checked={field.isPrimaryKey}
                          onChange={() => togglePrimaryKey(field.id)}
                        />
                        <label htmlFor={`pk-${field.id}`}>🔑 Primary Key</label>
                      </div>

                      {field.type === 'INTEGER' && field.isPrimaryKey && (
                        <div className="checkbox-group">
                          <input
                            type="checkbox"
                            id={`ai-${field.id}`}
                            checked={field.autoIncrement}
                            onChange={(e) =>
                              updateField(field.id, { autoIncrement: (e.target as HTMLInputElement).checked })
                            }
                          />
                          <label htmlFor={`ai-${field.id}`}>↗️ Auto Increment</label>
                        </div>
                      )}

                      <div className="checkbox-group">
                        <input
                          type="checkbox"
                          id={`nn-${field.id}`}
                          checked={field.notNull}
                          onChange={(e) =>
                            updateField(field.id, { notNull: (e.target as HTMLInputElement).checked })
                          }
                        />
                        <label htmlFor={`nn-${field.id}`}>⚠️ NOT NULL</label>
                      </div>

                      <div className="checkbox-group">
                        <input
                          type="checkbox"
                          id={`uq-${field.id}`}
                          checked={field.unique}
                          onChange={(e) =>
                            updateField(field.id, { unique: (e.target as HTMLInputElement).checked })
                          }
                        />
                        <label htmlFor={`uq-${field.id}`}>🔒 UNIQUE</label>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="sql-preview">
            <h4>SQL Preview</h4>
            <pre>
              <code>{sql}</code>
            </pre>
          </div>

        <div className="modal-footer">
          <Button type="button" onClick={handleClose} variant="secondary">
            Cancel
          </Button>
          <Button type="submit" variant="primary" disabled={loading}>
            {loading ? '⏳ Creating...' : '✨ Create Table'}
          </Button>
        </div>
      </form>
    </Modal>
  );
}
