// src/ui/components/DataBrowser/AddRowModal.tsx
import { useState, useEffect } from 'preact/hooks';
import { Modal, Button, Alert } from '../shared';
import { ApiClient } from '../../lib/api';
import { generateUUID } from '../../lib/utils';
import { useNotification } from '../../contexts/NotificationContext';
import { ColumnInfo, RowData } from '../../types';

interface AddRowModalProps {
  isOpen: boolean;
  onClose: () => void;
  apiClient: ApiClient;
  tableName: string;
  onSuccess: () => void;
}

export function AddRowModal({ isOpen, onClose, apiClient, tableName, onSuccess }: AddRowModalProps) {
  const { showToast } = useNotification();
  const [schema, setSchema] = useState<ColumnInfo[]>([]);
  const [formData, setFormData] = useState<RowData>({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [schemaLoading, setSchemaLoading] = useState(true);

  useEffect(() => {
    if (isOpen) {
      loadSchema();
    }
  }, [isOpen, tableName]);

  const loadSchema = async () => {
    setSchemaLoading(true);
    setError('');
    try {
      const result = await apiClient.getTableSchema(tableName);
      if (result.success && result.data) {
        const columns = Array.isArray(result.data) ? result.data : [];
        setSchema(columns);

        // Initialize form data with default values
        const initialData: RowData = {};
        columns.forEach((col) => {
          if (col.dflt_value !== null) {
            initialData[col.name] = col.dflt_value;
          } else {
            initialData[col.name] = '';
          }
        });
        setFormData(initialData);
      } else {
        throw new Error(result.error || 'Failed to load schema');
      }
    } catch (err: any) {
      setError(err.message || 'Failed to load table schema');
    } finally {
      setSchemaLoading(false);
    }
  };

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      // Process form data
      const submitData: Record<string, any> = {};

      schema.forEach((col) => {
        const value = formData[col.name];

        // Skip auto-increment primary keys
        if (col.pk && col.type === 'INTEGER' && (value === '' || value === null)) {
          return;
        }

        // Auto-generate UUID for TEXT primary keys if empty
        if (col.pk && col.type === 'TEXT' && (value === '' || value === null)) {
          submitData[col.name] = generateUUID();
          return;
        }

        // Handle empty values
        if (value === '' || value === null) {
          if (col.notnull && col.dflt_value === null) {
            throw new Error(`Field "${col.name}" is required`);
          }
          submitData[col.name] = null;
          return;
        }

        // Type conversion
        if (col.type === 'INTEGER') {
          const num = parseInt(String(value ?? ''), 10);
          if (isNaN(num)) {
            throw new Error(`Field "${col.name}" must be a number`);
          }
          submitData[col.name] = num;
        } else if (col.type === 'REAL') {
          const num = parseFloat(String(value ?? ''));
          if (isNaN(num)) {
            throw new Error(`Field "${col.name}" must be a number`);
          }
          submitData[col.name] = num;
        } else {
          submitData[col.name] = value;
        }
      });

      const result = await apiClient.insertRow(tableName, submitData);
      if (result.success) {
        showToast({ message: 'Row added successfully!', variant: 'success' });
        onSuccess();
        handleClose();
      } else {
        throw new Error(result.error || 'Failed to add row');
      }
    } catch (err: any) {
      setError(err.message || 'Failed to add row');
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setFormData({});
    setError('');
    onClose();
  };

  const updateField = (name: string, value: any) => {
    setFormData({ ...formData, [name]: value });
  };

  const shouldShowField = (col: ColumnInfo): boolean => {
    // Skip auto-increment INTEGER primary keys
    if (col.pk === 1 && col.type === 'INTEGER') {
      return false;
    }
    return true;
  };

  return (
    <Modal isOpen={isOpen} onClose={handleClose} title={`➕ Add Row to ${tableName}`} size="medium">
      <form onSubmit={handleSubmit}>
        {error && <Alert variant="danger">{error}</Alert>}

        {schemaLoading ? (
          <div className="loading">
            <div className="spinner"></div>
            <p>Loading schema...</p>
          </div>
        ) : (
          <div>
            {schema.filter(shouldShowField).map((col) => (
              <div key={col.name} className="form-group">
                <label htmlFor={`field-${col.name}`}>
                  {col.name}
                  {col.pk === 1 && <span style="color: var(--warning); margin-left: 4px;">🔑</span>}
                  {col.notnull === 1 && col.pk !== 1 && <span style="color: var(--danger); margin-left: 4px;">*</span>}
                  <span style="color: var(--text-light); font-size: 12px; margin-left: 8px;">
                    ({col.type})
                  </span>
                </label>
                <input
                  type="text"
                  id={`field-${col.name}`}
                  className="form-control"
                  value={String(formData[col.name] ?? '')}
                  onInput={(e) => updateField(col.name, (e.target as HTMLInputElement).value)}
                  placeholder={
                    col.pk === 1 && col.type === 'TEXT'
                      ? 'Leave empty to auto-generate UUID'
                      : col.dflt_value !== null
                      ? `Default: ${col.dflt_value}`
                      : col.notnull === 1
                      ? 'Required'
                      : 'Optional'
                  }
                />
              </div>
            ))}
          </div>
        )}

        <div className="modal-footer">
          <Button type="button" onClick={handleClose} variant="secondary" disabled={loading}>
            Cancel
          </Button>
          <Button type="submit" variant="success" disabled={loading || schemaLoading}>
            {loading ? '⏳ Adding...' : '✓ Add Row'}
          </Button>
        </div>
      </form>
    </Modal>
  );
}

// src/ui/components/data-browser/AddRowModal.vue
<template>
  <NModal v-model:show="show" :title="`Add Row — ${tableName}`" preset="card" style="width: 520px">
    <NSpin :show="schemaLoading">
      <NForm ref="formRef" :model="formData">
        <template v-for="col in visibleColumns" :key="col.name">
          <NFormItem
            :label="colLabel(col)"
            :path="col.name"
            :rule="colRule(col)"
          >
            <NInput v-model:value="formData[col.name]" :placeholder="colPlaceholder(col)" />
          </NFormItem>
        </template>
      </NForm>
    </NSpin>
    <NAlert v-if="error" type="error" :title="error" style="margin-top: 12px" />

    <template #footer>
      <NSpace justify="end">
        <NButton @click="show = false">Cancel</NButton>
        <NButton type="primary" :loading="loading" @click="handleSubmit">Add Row</NButton>
      </NSpace>
    </template>
  </NModal>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { NModal, NForm, NFormItem, NInput, NButton, NSpace, NAlert, NSpin, type FormInst } from 'naive-ui';
import { useAuthStore } from '@/stores/auth';
import { useTableSchema } from '@/composables/useTableSchema';
import type { ColumnInfo, RowData } from '@/types';

const props = defineProps<{ tableName: string }>();
const show = defineModel<boolean>('show', { default: false });
const emit = defineEmits<{ success: [] }>();

const authStore = useAuthStore();
const { schema, loading: schemaLoading } = useTableSchema(authStore.apiClient, () => props.tableName);

const formRef = ref<FormInst | null>(null);
const loading = ref(false);
const error = ref('');
const formData = ref<Record<string, string>>({});

// Skip auto-increment INTEGER primary keys
const visibleColumns = computed<ColumnInfo[]>(() =>
  schema.value.filter(col => !(col.pk && col.type?.toUpperCase() === 'INTEGER'))
);

watch(schema, (cols) => {
  const data: Record<string, string> = {};
  for (const col of cols) {
    if (col.pk && col.type?.toUpperCase() === 'INTEGER') continue;
    data[col.name] = col.dflt_value != null ? String(col.dflt_value) : '';
  }
  formData.value = data;
}, { immediate: true });

watch(show, (val) => { if (!val) error.value = ''; });

function colLabel(col: ColumnInfo) {
  const parts = [col.name];
  if (col.pk) parts.push('🔑');
  if (col.notnull && col.dflt_value == null) parts.push('*');
  return parts.join(' ');
}

function colPlaceholder(col: ColumnInfo) {
  if (col.dflt_value != null) return `Default: ${col.dflt_value}`;
  if (col.notnull) return 'Required';
  return 'Optional';
}

function colRule(col: ColumnInfo) {
  if (col.notnull && col.dflt_value == null) {
    return { required: true, message: `${col.name} is required`, trigger: 'blur' };
  }
  return undefined;
}

async function handleSubmit() {
  try { await formRef.value?.validate(); } catch { return; }
  loading.value = true; error.value = '';
  try {
    const payload: RowData = {};
    for (const col of visibleColumns.value) {
      const val = formData.value[col.name];
      if (val === '' || val === undefined) {
        if (col.notnull && col.dflt_value == null) { error.value = `${col.name} is required`; loading.value = false; return; }
        continue;
      }
      const t = col.type?.toUpperCase();
      if (t === 'INTEGER') payload[col.name] = parseInt(val);
      else if (t === 'REAL') payload[col.name] = parseFloat(val);
      else payload[col.name] = val;
    }
    const res = await authStore.apiClient.insertRow(props.tableName, payload);
    if (res.success !== false) {
      show.value = false;
      emit('success');
    } else {
      error.value = res.error ?? 'Failed to add row';
    }
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Failed to add row';
  } finally {
    loading.value = false;
  }
}
</script>
